<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '2b01d8c52f76d3e3cc1485dab88404f3',
  'DATABASE_URL' => 'mysql://spacexplore:pouet@192.168.1.5:3306/spacexplore?serverVersion=5.7',
);
